### ISSUE TITLE
No video on elementary OS

### ISSUE THREAD

**Issue by cassidyjames** [torikulhabib/niki#13]
Thanks for submitting your app to AppCenter! While reviewing, we were unable to get video to play back properly on any video we tried. We were stuck with a black window while audio played.

Is this something you've seen before?

**Comment by torikulhabib** [comment]
https://github.com/torikulhabib/niki/commit/b658fb2a844c609a18b7f4a0b82dfec68e3d24eb

**Comment by torikulhabib** [comment]
depends plugin gstreamer
