### ISSUE TITLE
Do not use constants for translations

### ISSUE THREAD

**Issue by NathanBnm** [torikulhabib/niki#15]
Using constants for translations is removing context for translators. I had some trouble translating your app into French. In addition, some strings are still not in the constants.

**Comment by torikulhabib** [comment]
Thanks,
i will fix soon!

**Comment by torikulhabib** [comment]
https://github.com/torikulhabib/niki/commit/a800331001eff00982a541105206c862da1fd0cf

**Comment by torikulhabib** [comment]
thanks
