### ISSUE TITLE
Show loading screen while importing folder content

### ISSUE THREAD

**Issue by NathanBnm** [torikulhabib/niki#22]
When opening my Music Library the FileChooser is stuck while the content is loaded. It would be better to have a loading screen instead.

**Comment by torikulhabib** [comment]
Good Idea. I will write the code now.

**Comment by torikulhabib** [comment]
https://github.com/torikulhabib/niki/commit/8f7761f8c8ea4e9d0e729ac80a5fbf40763e4ba1
