### ISSUE TITLE
Change required for AppCenter: OARS Social Info

### ISSUE THREAD

**Issue by cassidyjames** [torikulhabib/niki#25]
Thanks for submitting your app to AppCenter! While reviewing, we noticed your app contacts external servers for certain features. Because of this, your app **must** set its `social-info` OARS tag to `mild` or greater. You can ensure your app has accurate OARS data by using the [official OARS generator](https://hughsie.github.io/oars/).

https://github.com/torikulhabib/niki/blob/010c5ed9fa9efe49907fa4f0c166620cdb2a9153/data/com.github.torikulhabib.niki.appdata.xml.in#L94

**Comment by torikulhabib** [comment]
https://github.com/torikulhabib/niki/commit/919eecdf5852eb02b0d72b9198c8f68cfde52c25

**Comment by torikulhabib** [comment]
thanks
