### ISSUE TITLE
Cannot build on elementary 6 Daily

### ISSUE THREAD

**Issue by hanaral** [torikulhabib/niki#30]
The app still uses libgupnp-1.0 to build, while the only available one available on elementary 6 is 1.2.

**Comment by torikulhabib** [comment]
ok, i will migrate soon.

**Comment by hanaral** [comment]
Same goes for `gupnp-av-1.0` and `gssdp-1.0`

**Comment by torikulhabib** [comment]
https://github.com/torikulhabib/niki/commit/b87e49fc0340b7aba98b2a86f5d20db0515e57bb
thanks
