### ISSUE TITLE
Use more restrictive file permissions

### ISSUE THREAD

**Issue by danirabbit** [torikulhabib/niki#34]
Niki could use a lot more restricted file permissions by:
- [x] Switching from Gtk.FileChooser to Gtk.FileChooserNative which uses the file chooser portal
- [x] Changing `home` access in flatpak to individual library directories like `  - '--filesystem=xdg-videos'`

**Comment by torikulhabib** [comment]
ok
Hi @danrabbit i was made new app but appcenter don't give build status on dashboard developer
https://github.com/gabutakut/gabutdm

**Comment by danirabbit** [comment]
Ah yeah, sorry about that! I'll set up an import for that manually

**Comment by torikulhabib** [comment]
https://github.com/torikulhabib/niki/commit/ead992cf06b86609975774caa34bed93cc92cf4c
